### ISSUE TITLE
nOAuth Vulnerability (discussion)

### ISSUE THREAD

**Issue by FLX-0x00** [RIPAGlobal/omniauth-azure-activedirectory-v2#23]
Is this a thing that is covered in the gem or could this a security flaw? Have not tested the gem against the bug.

https://www.descope.com/blog/post/noauth

https://github.com/advisories/GHSA-5g66-628f-7cvj

**Comment by pond** [comment]
We don't and never have used an e-mail address to identify a user within our implementation, though what happens beyond that is up to the client software using our gem.

* OmniAuth clients are supposed to use [the UID returned by an OmniAuth strategy in the standardised hash](https://github.com/omniauth/omniauth/wiki/Auth-Hash-Schema) to uniquely identify users.
* The Azure integration uses the `oid` field for this, which in practice for the examples we have in our own client applications for Azure-AD-now-Entra, is a V4 UUID (e.g. ``).
* https://github.com/RIPAGlobal/omniauth-azure-activedirectory-v2/blob/master/lib/omniauth/strategies/azure_activedirectory_v2.rb#L64

This gem is not vulnerable to the attack, but client applications which were erroneously using an e-mail address instead of UID might well be. That's not something we have any visibility of, nor can police. The OmniAuth documentation is probably not clear enough on never relying on e-mail for association with a local User record, although the [aforementioned documentation of the auth hash schema](https://github.com/omniauth/omniauth/wiki/Auth-Hash-Schema) does indicate that `email` is optional and not always there, so developers at least have some hint that this would be a very bad choice!

**Comment by FLX-0x00** [comment]
Thanks for making this clear to me! I appreciate your time.
